language: ruby
branches:
  only:
    - master
cache:
  - bundler
install:
  - bundle install
script:
  - bundle exec jekyll build --config _config.yml
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
