# SEO settings
title: "ntdef"
description: "the blog of Troy de Freitas"
keywords: "blog, data science, analytics, machine learning, numpy, julialang, sklearn"
url: http://ntdef.com
baseurl: null
google_analytics: UA-47727049-1

repo: https://github.com/ntdef/ntdef.github.io
disqus_shortname: "ntdef"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Troy de Freitas
  job      : data scientist and machine learning engineer
  bio      : "If you’re in Chicago and you’d like to get coffee let me know! If you want to see what I’ve built you should look at my projects. While you’re there, you should take a look at Hume which I built to make deploying machine learning models a lot easier."
  thumb    : /images/author.jpg
  email    : me@ntdef.com
  url      : http://ntdef.com
  github   : http://github.com/ntdef
  linkedin : http://linkedin.com/in/ntdefreitas

og_locale: "en_US"

gems:
  - bourbon
  - jekyll-paginate

navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
